### ISSUE TITLE
Debugging after build of working code?

### ISSUE THREAD

**Issue by MikeHibbert** [nodegui/packer#138]
Hi

I've managed to build my app on MacOSX and it run using nom run fine but when I try 'open MyApp.app' it opens briefly then closes and shows a crash report that doesn't really give much away.

I used the console to cd into the MyApp.app/Contents/MacOS folder then then run ./qode but this just says:

```
 ./qode 
/Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/Resources
objc[17686]: Class QMacAutoReleasePoolTracker is implemented in both /Users/macbookair/Documents/nodejs/evermore-app/node_modules/@nodegui/nodegui/miniqt/5.14.1/clang_64/lib/QtCore.framework/Versions/5/QtCore (0x10613f030) and /Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10b5e0030). One of the two will be used. Which one is undefined.
objc[17686]: Class QT_ROOT_LEVEL_POOL__THESE_OBJECTS_WILL_BE_RELEASED_WHEN_QAPP_GOES_OUT_OF_SCOPE is implemented in both /Users/macbookair/Documents/nodejs/evermore-app/node_modules/@nodegui/nodegui/miniqt/5.14.1/clang_64/lib/QtCore.framework/Versions/5/QtCore (0x10613f0a8) and /Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10b5e00a8). One of the two will be used. Which one is undefined.
objc[17686]: Class KeyValueObserver is implemented in both /Users/macbookair/Documents/nodejs/evermore-app/node_modules/@nodegui/nodegui/miniqt/5.14.1/clang_64/lib/QtCore.framework/Versions/5/QtCore (0x10613f0d0) and /Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10b5e00d0). One of the two will be used. Which one is undefined.
objc[17686]: Class RunLoopModeTracker is implemented in both /Users/macbookair/Documents/nodejs/evermore-app/node_modules/@nodegui/nodegui/miniqt/5.14.1/clang_64/lib/QtCore.framework/Versions/5/QtCore (0x10613f120) and /Users/macbookair/Documents/nodejs/evermore-app/deploy/darwin/build/Evermore.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore (0x10b5e0120). One of the two will be used. Which one is undefined.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

Prior to that I was getting "Cannot find module 'regenerator-runtime'" from qode so I npm installed the module which caused nodegui to rebuild.

Is there a preferred way of debugging these issues once things have been packed?

**Comment by MikeHibbert** [comment]
Ok! so I did some digging and found that you can use lldb to get more meaningful information out ...

```
Error: Cannot find module 'regenerator-runtime'
Require stack:
- /Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/helpers.js
- /Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/db/helpers.js
- /Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/AddFile.js
- /Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/Init.js
- /Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/index.js
- /Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/index.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/helpers.js:10:50)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Module.require (internal/modules/cjs/loader.js:1080:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/helpers.js',
    '/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/db/helpers.js',
    '/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/AddFile.js',
    '/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/fsHandling/Init.js',
    '/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/dist/index.js',
    '/Users/macbookair/Documents/nodejs/Evermore.app/Contents/Resources/index.js',
    'internal/preload'
  ]
}
```

Looks like its not packing in the runtime I need because I use async functions in some cases.

Any advise?

**Comment by MikeHibbert** [comment]
I resolved this by removing the Imports from the effected files and added the runtime to the .babelrc so it appears its not a packer related issue just me being a numpty :)
